on:
  workflow_call:
    inputs:
      discussionCategory:
        description: The discussion category to use for release discussions
        type: string
        required: false
      makeTarget:
        description: The make target to run before publishing the release
        required: false
        type: string
      tag:
        description: The tag to publish the release from
        required: true
        type: string
      useReleaseActionMain:
        description: Whether to use the main branch of the release action
        required: false
        type: boolean
        default: false

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish release

    permissions:
      contents: write
      discussions: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: refs/tags/${{ inputs.tag }}

      - name: Check if tag is SemVer
        id: checkTag
        run: |
          if [[ "${{ inputs.tag }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo isSemVer=true >> $GITHUB_OUTPUT
            echo "Tag is SemVer"
          else
            echo "Tag is not SemVer"
          fi

      - name: Make
        if: ${{ inputs.makeTarget }}
        run: make ${{ inputs.makeTarget }}

      - name: Publish release
        if: "!inputs.useReleaseActionMain"
        uses: ghalactic/github-release-from-tag@v5
        with:
          reactions: hooray,heart,rocket
          discussionCategory: ${{ steps.checkTag.outputs.isSemVer == 'true' && inputs.discussionCategory || '' }}
          discussionReactions: ${{ (inputs.discussionCategory && steps.checkTag.outputs.isSemVer == 'true') && 'hooray,heart,rocket' || '' }}

      - name: Publish release (main)
        if: inputs.useReleaseActionMain
        uses: ghalactic/github-release-from-tag@main
        with:
          reactions: hooray,heart,rocket
          discussionCategory: ${{ steps.checkTag.outputs.isSemVer == 'true' && inputs.discussionCategory || '' }}
          discussionReactions: ${{ (inputs.discussionCategory && steps.checkTag.outputs.isSemVer == 'true') && 'hooray,heart,rocket' || '' }}
